[package]
name = "hv-tip-calculator"
version = "0.1.0"
edition = "2021"

[dependencies]

lambda_runtime = "0.13.0"
rust_decimal = "1.36.0"
rust_decimal_macros = "1.36.0"
serde = "1"
tokio = { version = "1", features = ["macros"] }
