[package]
name = "blkrs"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Shell for lsblk command"
documentation = "TBA"
homepage = "https://github.com/htv2012"

[dependencies]
clap = { version = "4.5.23", features = ["derive", "env"] }
serde_json = "1.0.133"
